### ISSUE TITLE
Does not load on startup with Tuinity

### ISSUE THREAD

**Issue by James76931** [J3fftw1/SoundMuffler#10]
Hi.

When the server starts, the plugin fails to load with this error:
```
[17:51:14 ERROR]: Error occurred while enabling SoundMuffler vDEV - 8 (git b700523d) (Is it up to date?)
java.lang.NoSuchMethodError: 'void dev.j3fftw.soundmuffler.SoundMufflerMachine.registerChargeableBlock(int)'
at dev.j3fftw.soundmuffler.SoundMuffler.onEnable(SoundMuffler.java:23) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Tuinity-"99854e9"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Tuinity-"99854e9"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Tuinity-"99854e9"]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Tuinity-"99854e9"]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Tuinity-"99854e9"]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Tuinity-"99854e9"]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Tuinity-"99854e9"]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Tuinity-"99854e9"]
at java.lang.Thread.run(Thread.java:834) [?:?]
[17:51:14 INFO]: [SoundMuffler] Disabling SoundMuffler vDEV - 8 (git b700523d)
```

I'm using Tuinity build 99854e9 (the latest version right now) and the most recent version of Slimefun4.

**Comment by Cyber-MC** [comment]
Update SoundMuffler to the 10th DEV build and see if it resolves the issue.
