### ISSUE TITLE
Error on the newest SF version

### ISSUE THREAD

**Issue by bobhenl** [J3fftw1/SoundMuffler#15]
```
[13:17:13] [Server thread/ERROR]: Error occurred while enabling SoundMuffler vDEV - 12 (git 7303b3a9) (Is it up to date?)
java.lang.NoSuchMethodError: 'void me.mrCookieSlime.Slimefun.api.Slimefun.registerResearch(me.mrCookieSlime.Slimefun.Objects.Research, org.bukkit.inventory.ItemStack[])'
	at dev.j3fftw.soundmuffler.SoundMuffler.onEnable(SoundMuffler.java:30) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

Plugin doesn't work
Minecraft Version: 1.16.1
CS-CoreLib Version: 88
Slimefun Version: 588
Plugin Version: 12

@J3fftw1

**Comment by NCBPFluffyBear** [comment]
Same issue here, running Paper 1.16.1.

```
[11:25:37 INFO]: Paper v1_16_R1
[11:25:37 INFO]:
[11:25:37 INFO]: CS-CoreLib vDEV - 88 (git 6a39a9e7)
[11:25:37 INFO]: Slimefun vDEV - 590 (git ee62a9b0)
[11:25:37 INFO]: Backwards compatiblity enabled!
[11:25:37 INFO]:
[11:25:37 INFO]: Installed Addons (5)
[11:25:37 INFO]:  LiteXpansion vDEV - 47 (git ec034a10)
[11:25:37 INFO]:  SoundMuffler vDEV - 12 (git 7303b3a9)
[11:25:37 INFO]:  TranscEndence vDEV - 17 (git 056982d3)
[11:25:37 INFO]:  SlimefunLuckyBlocks vDEV - 27 (git 2798a937)
[11:25:37 INFO]:  ChestTerminal vDEV - 33 (git fbb12c5c)
```

**Comment by Victorsueca** [comment]
I think I just reproduced this issue on my server. It's happening since a recent SlimeFun update.
Apparently something was changed in the SlimeFun code and this addon has not yet been updated to work with those changes.

```
[15:06:22 ERROR]: Error occurred while enabling SoundMuffler vDEV - 12 (git 7303b3a9) (Is it up to date?)
java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/Research
        at dev.j3fftw.soundmuffler.SoundMuffler.onEnable(SoundMuffler.java:30) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-113]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-113]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-113]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-113]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-113]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-113]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-113]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-113]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-113]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.Research
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-113]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-113]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        ... 11 more
```

**Comment by bobhenl** [comment]
Hi, how it looks @J3fftw1

**Comment by bobhenl** [comment]
@WalshyDev couldn't you look at it as Litexpansion dev please?
